_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": darwin-arm64
batch_size:
    value: 128
data_dir:
    value: FB15k-237
device:
    value: cuda
embedding_dim:
    value: 200
embedding_shape1:
    value: 20
epochs:
    value: 100
feature_map_dropout:
    value: 0.2
hidden_dropout:
    value: 0.3
input_dropout:
    value: 0.2
label_smoothing:
    value: 0.1
learning_rate:
    value: 0.001
num_workers:
    value: 4
